"""
Shopper Spectrum — Streamlit App
================================
Modules:
  1. Product Recommendation  — enter a product name → top 5 similar products
  2. Customer Segmentation   — enter RFM values → predict customer segment

Requirements:
  pip install streamlit pandas numpy scikit-learn joblib matplotlib seaborn plotly

Artefacts needed (generated by the notebook):
  kmeans_model.pkl
  scaler.pkl
  cluster_segment_map.pkl
  item_similarity.csv

Run:
  streamlit run app.py
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import os
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import plotly.graph_objects as go
import plotly.express as px
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics.pairwise import cosine_similarity

# ─────────────────────────────────────────────────────────────────────────────
# PAGE CONFIG
# ─────────────────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Shopper Spectrum",
    page_icon="🛒",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─────────────────────────────────────────────────────────────────────────────
# CUSTOM CSS
# ─────────────────────────────────────────────────────────────────────────────
st.markdown("""
<style>
    /* Main background */
    .main { background-color: #0f1117; }

    /* Sidebar */
    [data-testid="stSidebar"] {
        background: linear-gradient(160deg, #1a1f2e 0%, #12151f 100%);
        border-right: 1px solid #2a2f3e;
    }

    /* App title */
    .app-title {
        font-size: 2.6rem;
        font-weight: 800;
        background: linear-gradient(90deg, #7c3aed, #06b6d4, #10b981);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        background-clip: text;
        letter-spacing: -0.5px;
        margin-bottom: 0;
    }

    .app-subtitle {
        color: #94a3b8;
        font-size: 1rem;
        margin-top: 4px;
        margin-bottom: 1.5rem;
    }

    /* Section headers */
    .section-header {
        font-size: 1.4rem;
        font-weight: 700;
        color: #e2e8f0;
        margin-bottom: 0.3rem;
        padding-bottom: 0.4rem;
        border-bottom: 2px solid #7c3aed;
        display: inline-block;
    }

    /* Metric cards */
    .metric-card {
        background: linear-gradient(135deg, #1e2535 0%, #1a1f2e 100%);
        border: 1px solid #2d3448;
        border-radius: 12px;
        padding: 1.2rem 1.5rem;
        margin: 0.4rem 0;
        transition: border-color 0.2s;
    }
    .metric-card:hover { border-color: #7c3aed; }
    .metric-card .label {
        font-size: 0.75rem;
        text-transform: uppercase;
        letter-spacing: 1px;
        color: #64748b;
        margin-bottom: 4px;
    }
    .metric-card .value {
        font-size: 1.6rem;
        font-weight: 700;
        color: #e2e8f0;
    }

    /* Segment badge */
    .segment-badge {
        display: inline-block;
        padding: 0.4rem 1.2rem;
        border-radius: 999px;
        font-weight: 700;
        font-size: 1rem;
        letter-spacing: 0.5px;
        margin: 0.5rem 0;
    }

    /* Recommendation card */
    .rec-card {
        background: #1a1f2e;
        border: 1px solid #2d3448;
        border-left: 4px solid #7c3aed;
        border-radius: 8px;
        padding: 0.8rem 1.2rem;
        margin: 0.4rem 0;
        display: flex;
        justify-content: space-between;
        align-items: center;
    }
    .rec-card .rank {
        font-size: 1.2rem;
        font-weight: 800;
        color: #7c3aed;
        min-width: 2rem;
    }
    .rec-card .product-name {
        color: #e2e8f0;
        font-size: 0.95rem;
        flex: 1;
        padding: 0 1rem;
    }
    .rec-card .similarity {
        font-size: 0.85rem;
        color: #10b981;
        font-weight: 600;
        font-family: monospace;
    }

    /* Info box */
    .info-box {
        background: #1e2535;
        border: 1px solid #2d3448;
        border-radius: 10px;
        padding: 1rem 1.4rem;
        color: #94a3b8;
        font-size: 0.88rem;
        line-height: 1.6;
        margin-top: 0.8rem;
    }

    /* Divider */
    .divider {
        border: none;
        border-top: 1px solid #2a2f3e;
        margin: 1.5rem 0;
    }

    /* Override Streamlit default button */
    .stButton > button {
        background: linear-gradient(90deg, #7c3aed, #06b6d4);
        color: white;
        border: none;
        border-radius: 8px;
        font-weight: 700;
        font-size: 0.95rem;
        padding: 0.55rem 2rem;
        transition: opacity 0.2s;
    }
    .stButton > button:hover { opacity: 0.85; }

    /* Input label */
    label { color: #94a3b8 !important; font-size: 0.88rem !important; }

    /* Number input */
    .stNumberInput input { background: #1e2535 !important; color: #e2e8f0 !important; border-color: #2d3448 !important; }
    .stTextInput input   { background: #1e2535 !important; color: #e2e8f0 !important; border-color: #2d3448 !important; }
</style>
""", unsafe_allow_html=True)

# ─────────────────────────────────────────────────────────────────────────────
# SEGMENT CONFIG
# ─────────────────────────────────────────────────────────────────────────────
SEGMENT_CONFIG = {
    "High-Value": {
        "color"      : "#10b981",
        "bg"         : "rgba(16,185,129,0.15)",
        "icon"       : "🌟",
        "description": "Recent, frequent, and high-spending — your most profitable customers.",
        "strategy"   : "Reward with loyalty perks, early access to new products, and VIP campaigns.",
        "rfm_hint"   : "Low Recency · High Frequency · High Monetary",
    },
    "Regular": {
        "color"      : "#06b6d4",
        "bg"         : "rgba(6,182,212,0.15)",
        "icon"       : "📊",
        "description": "Steady purchasers with consistent buying behavior.",
        "strategy"   : "Upsell premium products and cross-sell complementary items to grow basket size.",
        "rfm_hint"   : "Medium Recency · Medium Frequency · Medium Monetary",
    },
    "Occasional": {
        "color"      : "#f59e0b",
        "bg"         : "rgba(245,158,11,0.15)",
        "icon"       : "⚠️",
        "description": "Infrequent buyers — potential to be nurtured into loyal customers.",
        "strategy"   : "Send targeted re-engagement emails with personalized offers and discounts.",
        "rfm_hint"   : "Medium Recency · Low Frequency · Low Monetary",
    },
    "At-Risk": {
        "color"      : "#ef4444",
        "bg"         : "rgba(239,68,68,0.15)",
        "icon"       : "🔴",
        "description": "Haven't purchased in a long time — at risk of churn.",
        "strategy"   : "Launch win-back campaigns with strong incentives (free shipping, discount codes).",
        "rfm_hint"   : "High Recency · Low Frequency · Low Monetary",
    },
}

# ─────────────────────────────────────────────────────────────────────────────
# LOAD ARTEFACTS  (with graceful fallback for demo mode)
# ─────────────────────────────────────────────────────────────────────────────
@st.cache_resource(show_spinner=False)
def load_artefacts():
    artefacts = {}
    missing   = []

    for fname in ["kmeans_model.pkl", "scaler.pkl", "cluster_segment_map.pkl"]:
        if os.path.exists(fname):
            artefacts[fname] = joblib.load(fname)
        else:
            missing.append(fname)

    if os.path.exists("item_similarity.csv"):
        artefacts["item_similarity.csv"] = pd.read_csv("item_similarity.csv", index_col=0)
    else:
        missing.append("item_similarity.csv")

    return artefacts, missing


artefacts, missing_files = load_artefacts()
demo_mode = len(missing_files) > 0

# ─────────────────────────────────────────────────────────────────────────────
# HELPER: predict segment
# ─────────────────────────────────────────────────────────────────────────────
def predict_segment(recency: int, frequency: int, monetary: float) -> str:
    if demo_mode:
        # Rule-based demo fallback
        if recency <= 30 and frequency >= 10 and monetary >= 1000:
            return "High-Value"
        elif recency <= 90 and frequency >= 4:
            return "Regular"
        elif recency <= 180:
            return "Occasional"
        else:
            return "At-Risk"

    scaler      = artefacts["scaler.pkl"]
    km          = artefacts["kmeans_model.pkl"]
    cluster_map = artefacts["cluster_segment_map.pkl"]

    features = np.array([[recency, np.log1p(frequency), np.log1p(monetary)]])
    scaled   = scaler.transform(features)
    cluster  = km.predict(scaled)[0]
    return cluster_map.get(cluster, "Unknown")


# ─────────────────────────────────────────────────────────────────────────────
# HELPER: recommend products
# ─────────────────────────────────────────────────────────────────────────────
def recommend_products(product_name: str, top_n: int = 5):
    if demo_mode or "item_similarity.csv" not in artefacts:
        # Static demo recommendations
        demo_recs = {
            "WHITE HANGING HEART T-LIGHT HOLDER": [
                ("RED HANGING HEART T-LIGHT HOLDER", 0.97),
                ("CREAM HANGING HEART T-LIGHT HOLDER", 0.93),
                ("PINK HANGING HEART T-LIGHT HOLDER", 0.91),
                ("WOODEN HEART CHRISTMAS DECORATION", 0.87),
                ("SET OF 6 HEART NAPKINS", 0.82),
            ]
        }
        return demo_recs.get(
            product_name.upper(),
            [(f"DEMO PRODUCT {i}", round(0.95 - i * 0.07, 2)) for i in range(1, top_n + 1)],
        )

    sim_df  = artefacts["item_similarity.csv"]
    product = product_name.strip().upper()

    if product not in sim_df.index:
        matches = [p for p in sim_df.index if product in p]
        if not matches:
            return None
        product = matches[0]

    similar = sim_df[product].sort_values(ascending=False).drop(product)
    return list(zip(similar.head(top_n).index, similar.head(top_n).values))


# ─────────────────────────────────────────────────────────────────────────────
# SIDEBAR
# ─────────────────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("""
        <div style='text-align:center; padding: 1rem 0 0.5rem;'>
            <div style='font-size:2.8rem;'>🛒</div>
            <div style='font-size:1.3rem; font-weight:800; color:#e2e8f0;'>Shopper Spectrum</div>
            <div style='font-size:0.78rem; color:#64748b; margin-top:4px;'>E-Commerce ML Platform</div>
        </div>
    """, unsafe_allow_html=True)

    st.markdown("<hr style='border-color:#2a2f3e; margin:1rem 0;'>", unsafe_allow_html=True)

    module = st.radio(
        "Choose Module",
        options=["🎯 Product Recommendation", "👥 Customer Segmentation"],
        index=0,
    )

    st.markdown("<hr style='border-color:#2a2f3e; margin:1rem 0;'>", unsafe_allow_html=True)

    # Segment legend
    st.markdown("<div style='color:#64748b; font-size:0.75rem; text-transform:uppercase; letter-spacing:1px; margin-bottom:0.6rem;'>Segment Guide</div>", unsafe_allow_html=True)
    for seg, cfg in SEGMENT_CONFIG.items():
        st.markdown(
            f"<div style='display:flex; align-items:center; gap:8px; margin-bottom:6px;'>"
            f"<div style='width:10px; height:10px; border-radius:50%; background:{cfg['color']};'></div>"
            f"<span style='color:#94a3b8; font-size:0.82rem;'>{cfg['icon']} {seg}</span>"
            f"</div>",
            unsafe_allow_html=True,
        )

    if demo_mode:
        st.markdown("<hr style='border-color:#2a2f3e; margin:1rem 0;'>", unsafe_allow_html=True)
        st.warning(f"**Demo Mode** — {len(missing_files)} artefact(s) not found.\n\nRun the notebook first to generate model files.")

# ─────────────────────────────────────────────────────────────────────────────
# MAIN HEADER
# ─────────────────────────────────────────────────────────────────────────────
st.markdown('<div class="app-title">Shopper Spectrum</div>', unsafe_allow_html=True)
st.markdown('<div class="app-subtitle">Customer Segmentation & Product Recommendations — E-Commerce ML Platform</div>', unsafe_allow_html=True)

if demo_mode:
    st.info(f"🔧 **Demo mode active** — missing: `{'`, `'.join(missing_files)}`. Run the notebook to generate these files. Predictions use rule-based fallback logic.", icon="ℹ️")

st.markdown("<hr style='border-color:#2a2f3e;'>", unsafe_allow_html=True)

# ─────────────────────────────────────────────────────────────────────────────
# MODULE 1: PRODUCT RECOMMENDATION
# ─────────────────────────────────────────────────────────────────────────────
if module == "🎯 Product Recommendation":
    st.markdown('<div class="section-header">🎯 Product Recommendation</div>', unsafe_allow_html=True)
    st.markdown("<br>", unsafe_allow_html=True)

    col_input, col_result = st.columns([1, 1.4], gap="large")

    with col_input:
        st.markdown("<div style='color:#94a3b8; font-size:0.88rem; margin-bottom:0.5rem;'>Enter a product name from the catalog to discover similar items customers also purchased.</div>", unsafe_allow_html=True)

        product_input = st.text_input(
            "Product Name",
            value="WHITE HANGING HEART T-LIGHT HOLDER",
            placeholder="e.g. CERAMIC STORAGE JAR",
        )

        top_n = st.slider("Number of recommendations", min_value=3, max_value=10, value=5)

        run_rec = st.button("Get Recommendations →", use_container_width=True)

        st.markdown("""
        <div class="info-box">
            <strong style='color:#e2e8f0;'>How it works</strong><br>
            Item-Based Collaborative Filtering computes cosine similarity between products 
            based on co-purchase patterns across all customers. Products bought together 
            frequently score higher similarity.
        </div>
        """, unsafe_allow_html=True)

    with col_result:
        if run_rec and product_input.strip():
            with st.spinner("Finding similar products…"):
                results = recommend_products(product_input, top_n=top_n)

            if results is None:
                st.error(f"❌ Product **'{product_input.upper()}'** not found in the catalog.\n\nTry a different product name.")
            else:
                st.markdown(f"<div style='color:#94a3b8; font-size:0.85rem; margin-bottom:0.8rem;'>Top {top_n} products similar to <span style='color:#e2e8f0; font-weight:600;'>{product_input.upper()}</span></div>", unsafe_allow_html=True)

                scores = [score for _, score in results]
                max_score = max(scores) if scores else 1

                for i, (product, score) in enumerate(results, 1):
                    bar_pct = int((score / max_score) * 100)
                    st.markdown(f"""
                    <div class="rec-card">
                        <div class="rank">#{i}</div>
                        <div class="product-name">{product}</div>
                        <div class="similarity">{score:.4f}</div>
                    </div>
                    <div style='background:#2d3448; border-radius:4px; height:4px; margin: -6px 0 6px 3rem;'>
                        <div style='background:linear-gradient(90deg,#7c3aed,#06b6d4); width:{bar_pct}%; height:4px; border-radius:4px;'></div>
                    </div>
                    """, unsafe_allow_html=True)

                # Plotly bar chart
                st.markdown("<div style='margin-top:1.2rem;'>", unsafe_allow_html=True)
                products_list = [p for p, _ in results]
                scores_list   = [s for _, s in results]

                fig = go.Figure(go.Bar(
                    x=scores_list[::-1],
                    y=[p[:35] + "…" if len(p) > 35 else p for p in products_list[::-1]],
                    orientation='h',
                    marker=dict(
                        color=scores_list[::-1],
                        colorscale=[[0, '#7c3aed'], [1, '#10b981']],
                        showscale=False,
                    ),
                    text=[f"{s:.3f}" for s in scores_list[::-1]],
                    textposition='outside',
                ))
                fig.update_layout(
                    title=dict(text="Cosine Similarity Scores", font=dict(color='#94a3b8', size=13)),
                    paper_bgcolor='rgba(0,0,0,0)',
                    plot_bgcolor='rgba(0,0,0,0)',
                    font=dict(color='#94a3b8', size=11),
                    xaxis=dict(showgrid=True, gridcolor='#2d3448', range=[0, 1.1]),
                    yaxis=dict(showgrid=False),
                    height=280,
                    margin=dict(l=10, r=60, t=40, b=10),
                )
                st.plotly_chart(fig, use_container_width=True)
                st.markdown("</div>", unsafe_allow_html=True)
        else:
            st.markdown("""
            <div style='display:flex; flex-direction:column; align-items:center; justify-content:center; 
                        height:300px; color:#2d3448; text-align:center;'>
                <div style='font-size:3rem;'>🔍</div>
                <div style='font-size:0.95rem; margin-top:0.8rem; color:#3d4455;'>
                    Enter a product name and click<br><strong style='color:#4a5568;'>Get Recommendations</strong>
                </div>
            </div>
            """, unsafe_allow_html=True)

# ─────────────────────────────────────────────────────────────────────────────
# MODULE 2: CUSTOMER SEGMENTATION
# ─────────────────────────────────────────────────────────────────────────────
else:
    st.markdown('<div class="section-header">👥 Customer Segmentation</div>', unsafe_allow_html=True)
    st.markdown("<br>", unsafe_allow_html=True)

    col_form, col_result = st.columns([1, 1.4], gap="large")

    with col_form:
        st.markdown("<div style='color:#94a3b8; font-size:0.88rem; margin-bottom:1rem;'>Enter the customer's RFM metrics to predict their segment and receive a tailored strategy.</div>", unsafe_allow_html=True)

        recency   = st.number_input("Recency — days since last purchase", min_value=0, max_value=1000, value=30, step=1)
        frequency = st.number_input("Frequency — number of orders placed", min_value=1, max_value=500,  value=8,  step=1)
        monetary  = st.number_input("Monetary — total spend (£)", min_value=0.0, max_value=100000.0, value=850.0, step=10.0)

        run_seg = st.button("Predict Segment →", use_container_width=True)

        st.markdown("""
        <div class="info-box">
            <strong style='color:#e2e8f0;'>RFM Framework</strong><br>
            <b style='color:#e2e8f0;'>R</b>ecency — how recently did the customer buy?<br>
            <b style='color:#e2e8f0;'>F</b>requency — how often do they buy?<br>
            <b style='color:#e2e8f0;'>M</b>onetary — how much do they spend in total?<br><br>
            KMeans clustering on log-normalized, standardized RFM features assigns each customer to one of 4 segments.
        </div>
        """, unsafe_allow_html=True)

    with col_result:
        if run_seg:
            with st.spinner("Running segmentation model…"):
                segment = predict_segment(recency, frequency, monetary)

            cfg = SEGMENT_CONFIG.get(segment, SEGMENT_CONFIG["Regular"])

            st.markdown(f"""
            <div style='background:{cfg["bg"]}; border:1px solid {cfg["color"]}40; border-radius:14px; padding:1.5rem; margin-bottom:1rem;'>
                <div style='font-size:2.5rem; margin-bottom:0.5rem;'>{cfg["icon"]}</div>
                <div style='font-size:0.75rem; text-transform:uppercase; letter-spacing:1.5px; color:{cfg["color"]}; margin-bottom:4px;'>Predicted Segment</div>
                <div style='font-size:2rem; font-weight:800; color:#e2e8f0; margin-bottom:0.5rem;'>{segment}</div>
                <div style='font-size:0.9rem; color:#94a3b8;'>{cfg["description"]}</div>
            </div>
            """, unsafe_allow_html=True)

            st.markdown(f"""
            <div style='background:#1e2535; border:1px solid #2d3448; border-radius:10px; padding:1.1rem 1.4rem; margin-bottom:1rem;'>
                <div style='font-size:0.75rem; text-transform:uppercase; letter-spacing:1px; color:#64748b; margin-bottom:6px;'>Recommended Strategy</div>
                <div style='color:#e2e8f0; font-size:0.92rem;'>{cfg["strategy"]}</div>
            </div>
            """, unsafe_allow_html=True)

            # RFM gauge chart
            st.markdown("<div style='color:#64748b; font-size:0.75rem; text-transform:uppercase; letter-spacing:1px; margin-bottom:0.5rem;'>Input RFM Profile</div>", unsafe_allow_html=True)

            r_norm = max(0, min(100, int(100 - recency / 365 * 100)))
            f_norm = max(0, min(100, int(frequency / 50  * 100)))
            m_norm = max(0, min(100, int(monetary / 5000 * 100)))

            fig2 = go.Figure()
            for label, val, color in [("Recency Score", r_norm, "#7c3aed"),
                                       ("Frequency Score", f_norm, "#06b6d4"),
                                       ("Monetary Score", m_norm, "#10b981")]:
                fig2.add_trace(go.Bar(
                    name=label, x=[val], y=[label],
                    orientation='h',
                    marker=dict(color=color),
                    text=f"{val}",
                    textposition='outside',
                ))
            fig2.update_layout(
                showlegend=False,
                paper_bgcolor='rgba(0,0,0,0)',
                plot_bgcolor='rgba(0,0,0,0)',
                font=dict(color='#94a3b8', size=11),
                xaxis=dict(range=[0, 115], showgrid=True, gridcolor='#2d3448', title="Score (0–100)"),
                yaxis=dict(showgrid=False),
                height=200,
                margin=dict(l=10, r=60, t=20, b=10),
                barmode='group',
            )
            st.plotly_chart(fig2, use_container_width=True)

            # All segments comparison
            st.markdown("<div style='color:#64748b; font-size:0.75rem; text-transform:uppercase; letter-spacing:1px; margin:0.8rem 0 0.5rem;'>Segment Overview</div>", unsafe_allow_html=True)

            seg_data = {
                "Segment"  : list(SEGMENT_CONFIG.keys()),
                "Recency"  : [15,   60,  150, 300],
                "Frequency": [25,    8,    3,   1],
                "Monetary" : [4500, 900,  200,  80],
            }
            seg_df = pd.DataFrame(seg_data)

            fig3 = px.scatter(
                seg_df, x="Recency", y="Monetary", size="Frequency",
                color="Segment",
                color_discrete_map={
                    "High-Value" : "#10b981",
                    "Regular"    : "#06b6d4",
                    "Occasional" : "#f59e0b",
                    "At-Risk"    : "#ef4444",
                },
                hover_data=["Frequency"],
                size_max=50,
            )
            # Add user point
            fig3.add_trace(go.Scatter(
                x=[recency], y=[monetary],
                mode='markers+text',
                marker=dict(symbol='star', size=18, color='#ffffff', line=dict(color=cfg["color"], width=2)),
                text=["← You"], textposition="middle right",
                textfont=dict(color='#e2e8f0', size=11),
                name="This Customer",
                showlegend=True,
            ))
            fig3.update_layout(
                paper_bgcolor='rgba(0,0,0,0)',
                plot_bgcolor='rgba(0,0,0,0)',
                font=dict(color='#94a3b8', size=11),
                xaxis=dict(showgrid=True, gridcolor='#2d3448', title="Recency (days) →"),
                yaxis=dict(showgrid=True, gridcolor='#2d3448', title="Monetary (£) →"),
                height=260,
                margin=dict(l=10, r=10, t=20, b=10),
                legend=dict(font=dict(size=10), bgcolor='rgba(0,0,0,0)'),
            )
            st.plotly_chart(fig3, use_container_width=True)

        else:
            # Empty state
            st.markdown("""
            <div style='display:flex; flex-direction:column; align-items:center; justify-content:center;
                        height:360px; color:#2d3448; text-align:center;'>
                <div style='font-size:3rem;'>👤</div>
                <div style='font-size:0.95rem; margin-top:0.8rem; color:#3d4455;'>
                    Enter RFM values and click<br>
                    <strong style='color:#4a5568;'>Predict Segment</strong>
                </div>
            </div>
            """, unsafe_allow_html=True)

# ─────────────────────────────────────────────────────────────────────────────
# FOOTER
# ─────────────────────────────────────────────────────────────────────────────
st.markdown("<hr style='border-color:#2a2f3e; margin-top:2rem;'>", unsafe_allow_html=True)
st.markdown("""
<div style='display:flex; justify-content:space-between; align-items:center; padding:0.5rem 0;'>
    <div style='color:#3d4455; font-size:0.78rem;'>
        🛒 Shopper Spectrum — E-Commerce Customer Segmentation & Recommendation System
    </div>
    <div style='color:#3d4455; font-size:0.78rem;'>
        KMeans · Cosine Similarity · RFM Analysis
    </div>
</div>
""", unsafe_allow_html=True)